<?php
/**
 * Generated by framework installer - Sat, 05 Nov 2016 19:03:09 +0100
*/
    class Config
    {
	const BASEDNAME	= '/webproject';
	const DBHOST	= 'localhost';
	const DB	= 'webproject';
	const DBUSER	= 'root';
	const DBPW	= 'password';
	const SITENAME	= 'webproject';
	const SITEURL	= 'www.webproject.com';
	const SITENOREPLY	= 'noreply@webproject.ncl.ac.uk';
	const SYSADMIN	= 'l.rickayzen1@newcastle.ac.uk';
	const DBOP	= '=';
	const UPUBLIC	= TRUE;
	const UPRIVATE	= TRUE;

	public static function setup()
	{
	    Web::getinstance()->addheader([
		'Date'			=> gmstrftime('%b %d %Y %H:%M:%S', time()),
		'Window-target'		=> '_top',	# deframes things
		'X-Frame-Options'	=> 'DENY',	# deframes things
		'Content-Language'	=> 'en',
		'Vary'			=> 'Accept-Encoding',
	    ]);
	}
    }
?>